### ISSUE TITLE
Not able to upload diaQTL_fitQTL_list.RData in viewpoly

### ISSUE THREAD

**Issue by Gill-Amrit** [mmollina/viewpoly#40]
Hello!
My diaQTL_fitQTL_list.RData file is 12GB and when I try to upload the file in viewpoly it says the maximum limit exceeded. Could you please help me with this?

**Comment by Cristianetaniguti** [comment]
Hello! I just increased the upload file size limit to 50Gb, please install again using:
devtools::install_github("mmollina/viewpoly", ref = "add_hidecan")

**Comment by Cristianetaniguti** [comment]
Hello again @Gill-Amrit , I suggest you upload your large files (it will take a while) and submit them. Once you do that, VIEWpoly will convert all the files that you uploaded to the VIEWpoly object that contains only the information that it uses (a much smaller object).  There is a box for downloading this VIEWpoly object in the "input data" tab. In future consultations, you just need to upload this single VIEWpoly object. This will make your experience more smooth.
